//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("First_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon _4174_200 {
            get {
                object obj = ResourceManager.GetObject("_4174_200", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap human {
            get {
                object obj = ResourceManager.GetObject("human", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0100000000000000000000000000000000000000000000000000
        ///1010000000000000000000000000000000000000000000000000
        ///0101000000000000000000000000000000000000000000000000
        ///0010100000000000000000000000000000000000000000000000
        ///0001010000000000000000000000000000000000000000000000
        ///0000101000000000000000000000000000000000000000000000
        ///0000010100000000000000000000000000000000000000000000
        ///0000001010000000000000000000000000000000000000000000
        ///0000000101000000000000000000000000000000000000000000
        ///00000000101000000000020000 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string metroGraph {
            get {
                return ResourceManager.GetString("metroGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap metroMap {
            get {
                object obj = ResourceManager.GetObject("metroMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Академгородок,Житомирская,Святошино,Нивки,Берестейская,Шулявская,Политехнический институт,Вокзальная,Университет,Театральная,Крещатик,Арсенальная,Днепр,Гидропарк,Левобережная,Дарница,Черниговская,Лесная,Сырец,Дорогожичи,Лукьяновская,Золотые ворота,Дворец спорта,Кловская,Печерская,Дружбы народов,Выдубичи,Славутич,Осокорки,Позняки,Харьковская,Вырлица,Бориспольская,Красный Хутор,Героев Днепра,Минская,Оболонь,Петровка,Тараса Шевченко,Контрактовая Площадь,Почтовая Площадь,Площадь Независимости,Площадь Льва Толст [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string metroNames {
            get {
                return ResourceManager.GetString("metroNames", resourceCulture);
            }
        }
    }
}
